# Generated by Django 4.2.30 on 2026-07-04 02:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        (
            "greenhouse",
            "0003_remove_environmentreading_uniq_greenhouse_reading_recorded_source_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="DtuIngestAuditEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "external_device_id",
                    models.CharField(blank=True, db_index=True, max_length=128),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("accepted", "Accepted"), ("rejected", "Rejected")],
                        db_index=True,
                        max_length=16,
                    ),
                ),
                (
                    "error_code",
                    models.CharField(blank=True, db_index=True, max_length=64),
                ),
                (
                    "remote_ip",
                    models.GenericIPAddressField(blank=True, db_index=True, null=True),
                ),
                ("protocol", models.CharField(blank=True, max_length=32)),
                (
                    "frame_hash",
                    models.CharField(blank=True, db_index=True, max_length=64),
                ),
                ("redacted_snippet", models.CharField(blank=True, max_length=256)),
                ("details", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "device",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="dtu_ingest_events",
                        to="greenhouse.device",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
                "indexes": [
                    models.Index(
                        fields=["status", "-created_at"],
                        name="ingest_dtui_status_97b750_idx",
                    ),
                    models.Index(
                        fields=["external_device_id", "-created_at"],
                        name="ingest_dtui_externa_001503_idx",
                    ),
                    models.Index(
                        fields=["error_code", "-created_at"],
                        name="ingest_dtui_error_c_0616b7_idx",
                    ),
                ],
            },
        ),
    ]
