# Generated by Django 4.2.30 on 2026-06-27 08:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Greenhouse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=64, unique=True)),
                ("name", models.CharField(max_length=128)),
                ("location", models.CharField(blank=True, max_length=255)),
                (
                    "crop_code",
                    models.CharField(blank=True, db_index=True, max_length=64),
                ),
                (
                    "source",
                    models.CharField(db_index=True, default="local", max_length=32),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["code"],
                "indexes": [
                    models.Index(fields=["code"], name="greenhouse__code_324927_idx"),
                    models.Index(
                        fields=["crop_code", "source"],
                        name="greenhouse__crop_co_0204b2_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="DashboardSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("snapshot_at", models.DateTimeField(db_index=True)),
                ("payload", models.JSONField()),
                (
                    "schema_version",
                    models.CharField(default="dashboard-v1", max_length=32),
                ),
                (
                    "source",
                    models.CharField(db_index=True, default="local", max_length=32),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "greenhouse",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dashboard_snapshots",
                        to="greenhouse.greenhouse",
                    ),
                ),
            ],
            options={
                "ordering": ["-snapshot_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="EnvironmentReading",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("recorded_at", models.DateTimeField(db_index=True)),
                (
                    "air_temp",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
                (
                    "air_humidity",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
                (
                    "light",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "co2",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "soil_humidity",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
                (
                    "soil_temp",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
                (
                    "ec",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=8, null=True
                    ),
                ),
                (
                    "ph",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=6, null=True
                    ),
                ),
                (
                    "source",
                    models.CharField(db_index=True, default="local", max_length=32),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "greenhouse",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="readings",
                        to="greenhouse.greenhouse",
                    ),
                ),
            ],
            options={
                "ordering": ["-recorded_at", "greenhouse_id"],
                "indexes": [
                    models.Index(
                        fields=["greenhouse", "recorded_at"],
                        name="greenhouse__greenho_7e101f_idx",
                    ),
                    models.Index(
                        fields=["source", "recorded_at"],
                        name="greenhouse__source_51522b_idx",
                    ),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="environmentreading",
            constraint=models.UniqueConstraint(
                fields=("greenhouse", "recorded_at", "source"),
                name="uniq_greenhouse_reading_recorded_source",
            ),
        ),
        migrations.AddIndex(
            model_name="dashboardsnapshot",
            index=models.Index(
                fields=["source", "schema_version", "-snapshot_at"],
                name="greenhouse__source_93d550_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="dashboardsnapshot",
            constraint=models.UniqueConstraint(
                fields=("source", "schema_version", "snapshot_at"),
                name="uniq_dashboard_snapshot_source_schema_time",
            ),
        ),
    ]
