# Generated by Django 4.2.30 on 2026-07-03 06:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("greenhouse", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Alert",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("notice", "Notice"),
                            ("warning", "Warning"),
                            ("critical", "Critical"),
                        ],
                        db_index=True,
                        default="warning",
                        max_length=16,
                    ),
                ),
                (
                    "metric_type",
                    models.CharField(blank=True, db_index=True, max_length=32),
                ),
                ("message", models.CharField(max_length=512)),
                ("triggered_at", models.DateTimeField(db_index=True)),
                (
                    "resolved_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                (
                    "source",
                    models.CharField(db_index=True, default="local", max_length=32),
                ),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-triggered_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="Device",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=128, unique=True)),
                ("name", models.CharField(max_length=128)),
                (
                    "provider",
                    models.CharField(db_index=True, default="local", max_length=32),
                ),
                (
                    "external_id",
                    models.CharField(blank=True, db_index=True, max_length=128),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("online", "Online"),
                            ("warning", "Warning"),
                            ("offline", "Offline"),
                        ],
                        db_index=True,
                        default="online",
                        max_length=16,
                    ),
                ),
                (
                    "last_seen_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["greenhouse__code", "code"],
            },
        ),
        migrations.AddField(
            model_name="environmentreading",
            name="metric_type",
            field=models.CharField(db_index=True, default="environment", max_length=32),
        ),
        migrations.AddIndex(
            model_name="environmentreading",
            index=models.Index(
                fields=["greenhouse", "metric_type", "recorded_at"],
                name="greenhouse__greenho_825b15_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="environmentreading",
            index=models.Index(
                fields=["source", "metric_type", "recorded_at"],
                name="greenhouse__source_714e44_idx",
            ),
        ),
        migrations.AddField(
            model_name="device",
            name="greenhouse",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="devices",
                to="greenhouse.greenhouse",
            ),
        ),
        migrations.AddField(
            model_name="alert",
            name="device",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="alerts",
                to="greenhouse.device",
            ),
        ),
        migrations.AddField(
            model_name="alert",
            name="greenhouse",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="alerts",
                to="greenhouse.greenhouse",
            ),
        ),
        migrations.AddIndex(
            model_name="device",
            index=models.Index(
                fields=["greenhouse", "status"], name="greenhouse__greenho_c9ac60_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="device",
            index=models.Index(
                fields=["provider", "external_id"],
                name="greenhouse__provide_0204b3_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="device",
            index=models.Index(
                fields=["provider", "last_seen_at"],
                name="greenhouse__provide_76eda4_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="alert",
            index=models.Index(
                fields=["greenhouse", "resolved_at", "-triggered_at"],
                name="greenhouse__greenho_3ba628_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="alert",
            index=models.Index(
                fields=["greenhouse", "metric_type", "-triggered_at"],
                name="greenhouse__greenho_e42839_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="alert",
            index=models.Index(
                fields=["level", "resolved_at"], name="greenhouse__level_212999_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="alert",
            index=models.Index(
                fields=["source", "-triggered_at"], name="greenhouse__source_21611c_idx"
            ),
        ),
    ]
