# Generated by Django 4.2.30 on 2026-07-04 02:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("greenhouse", "0002_alert_device_environmentreading_metric_type_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="environmentreading",
            name="uniq_greenhouse_reading_recorded_source",
        ),
        migrations.AddField(
            model_name="device",
            name="ingest_allowed_ips",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="device",
            name="ingest_enabled",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name="device",
            name="ingest_protocol",
            field=models.CharField(default="smart_agri_v1", max_length=32),
        ),
        migrations.AddField(
            model_name="device",
            name="ingest_token_hash",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name="device",
            name="last_ingest_at",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name="environmentreading",
            name="device",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="readings",
                to="greenhouse.device",
            ),
        ),
        migrations.AddIndex(
            model_name="device",
            index=models.Index(
                fields=["provider", "ingest_enabled"],
                name="greenhouse__provide_285fe8_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="environmentreading",
            index=models.Index(
                fields=["device", "recorded_at"], name="greenhouse__device__766a64_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="environmentreading",
            constraint=models.UniqueConstraint(
                fields=("greenhouse", "device", "recorded_at", "source"),
                name="uniq_greenhouse_device_reading_source",
            ),
        ),
    ]
