# Generated by Django 4.2.30 on 2026-07-03 02:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="WeChatUserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("openid", models.CharField(max_length=128, unique=True)),
                (
                    "unionid",
                    models.CharField(blank=True, db_index=True, max_length=128),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("admin", "Admin"),
                            ("operator", "Operator"),
                            ("viewer", "Viewer"),
                        ],
                        db_index=True,
                        default="viewer",
                        max_length=32,
                    ),
                ),
                ("nickname", models.CharField(blank=True, max_length=128)),
                ("session_key_hash", models.CharField(blank=True, max_length=64)),
                ("last_login_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wechat_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["openid"],
                "indexes": [
                    models.Index(
                        fields=["openid"], name="accounts_we_openid_c35e5e_idx"
                    ),
                    models.Index(fields=["role"], name="accounts_we_role_e16c11_idx"),
                ],
            },
        ),
    ]
