# Generated by Django 4.2.30 on 2026-07-03 12:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UploadAsset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("original_name", models.CharField(max_length=255)),
                ("stored_name", models.CharField(max_length=255)),
                ("storage_key", models.CharField(max_length=512, unique=True)),
                (
                    "storage_backend",
                    models.CharField(
                        choices=[
                            ("local_private", "Local private filesystem"),
                            ("minio_private", "MinIO private bucket"),
                        ],
                        default="local_private",
                        max_length=32,
                    ),
                ),
                ("content_type", models.CharField(max_length=128)),
                ("detected_content_type", models.CharField(max_length=128)),
                ("extension", models.CharField(max_length=16)),
                ("size_bytes", models.PositiveBigIntegerField()),
                ("sha256", models.CharField(db_index=True, max_length=64)),
                (
                    "scan_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("clean", "Clean"),
                            ("infected", "Infected"),
                            ("scan_unavailable", "Scan unavailable"),
                            ("failed", "Failed"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=32,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ai_upload_assets",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="UploadScanTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("engine", models.CharField(default="clamav", max_length=64)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("clean", "Clean"),
                            ("infected", "Infected"),
                            ("unavailable", "Unavailable"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=32,
                    ),
                ),
                (
                    "policy",
                    models.CharField(default="hold_until_scanned", max_length=64),
                ),
                ("details", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "asset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scan_tasks",
                        to="ai_advisory.uploadasset",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["status", "created_at"],
                        name="ai_advisory_status_9b2fa5_idx",
                    ),
                    models.Index(
                        fields=["engine", "status"],
                        name="ai_advisory_engine_2afdde_idx",
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="uploadasset",
            index=models.Index(
                fields=["created_at"], name="ai_advisory_created_06286d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="uploadasset",
            index=models.Index(
                fields=["scan_status", "created_at"],
                name="ai_advisory_scan_st_50a1b5_idx",
            ),
        ),
    ]
